# Generated by Django 5.1.4 on 2025-01-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='message',
            field=models.TextField(default='Nothing was submitted by this user', max_length=500),
        ),
    ]
